Parameters:
  JenkinsVpc:
    Type: AWS::EC2::VPC::Id
  JenkinsSubnet:
    Type: AWS::EC2::Subnet::Id
  EksVpc:
    Type: AWS::EC2::VPC::Id
  EksSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  SonarQubeSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SonarQubeSubnet:
    Type: AWS::EC2::Subnet::Id

Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dfcb1ef8550277af
      InstanceType: t2.medium
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo wget -O /etc/yum.repos.d/jenkins.repo \
            https://pkg.jenkins.io/redhat-stable/jenkins.repo
          sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
          sudo yum upgrade -y
          sudo amazon-linux-extras install java-openjdk11 -y
          sudo yum install jenkins -y
          sudo systemctl enable jenkins
          sudo systemctl start jenkins
          sudo systemctl status jenkins
          sudo amazon-linux-extras install docker -y & sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo yum install maven -y       
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref JenkinsSecurityGroup
          SubnetId: !Ref JenkinsSubnet
      IamInstanceProfile: LabInstanceProfile
    #DependsOn: JenkinsEipAssociation
  SonarQubeInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b3a288fe7d63bf8a
      InstanceType: t2.medium
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref SonarQubeSecurityGroup
          SubnetId: !Ref SonarQubeSubnet
      IamInstanceProfile: LabInstanceProfile  
    #DependsOn: SonarQubeEipAssociation

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: eks-cluster
      RoleArn: arn:aws:iam::609565384919:role/LabRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksSecurityGroup
        SubnetIds: 
          - subnet-05e0f0b18693bb587
          - subnet-0e8ba44d4762e8f83
      Version: "1.25"
  JenkinsEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: "Name"
          Value: "JenkinsEIP"
  JenkinsEipAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref JenkinsInstance
      AllocationId: !GetAtt JenkinsEip.AllocationId

  SonarQubeEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: "Name"
          Value: "SonarQubeEIP"
  SonarQubeEipAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref SonarQubeInstance
      AllocationId: !GetAtt SonarQubeEip.AllocationId
  EksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EksCluster
      NodegroupName: my-node-group
      NodeRole: arn:aws:iam::609565384919:role/LabRole
      Subnets:
        - subnet-05e0f0b18693bb587
        - subnet-0e8ba44d4762e8f83
      ScalingConfig:
        DesiredSize: 1
        MaxSize: 2
        MinSize: 1
      InstanceTypes:
        - t2.medium
      Tags:
        Name: my-node-group

##output the urls
Outputs:
  JenkinsInstancePublicIp:
    Value: !GetAtt JenkinsEip.PublicIp
    Description: Public IP address of the Jenkins instance
  EksClusterName:
    Value: !Ref EksCluster
    Description: Name of the EKS cluster
  SonarQubeEip:
    Value: !GetAtt SonarQubeEip.PublicIp

